/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ctoeplitz_reg_h
#define _ctoeplitz_reg_h


void ctoeplitz_inv(int n, float mu, sf_complex *c, sf_complex *mm, sf_complex *dd);
/*< linear equation solver with FFT based on Toeplitz structure
  C*mm=dd, C=circulant(c): mm=C^{-1}dd 
  C=F^* diag(c) F 
  ==> C=F^* diag(1./c ) F 
  ==> mm=F^* diag(conj(c)./(c*conj(c) +mu)) F dd
  Here, mu is a stabalizing factor. Setting mu=0 implies no regularization.
  >*/

#endif
