/* This file is automatically generated. DO NOT EDIT! */

void ctoeplitz_inv(int n, double mu, complex *c, complex *mm, complex *dd);
/*< linear equation solver with FFT based on Toeplitz structure
  C*mm=dd, C=circulant(c): mm=C^{-1}dd 
  C=F^* diag(c) F 
  ==> C=F^* diag(1./c ) F 
  ==> mm=F^* diag(conj(c)./(c*conj(c) +mu)) F dd
  Here, mu is a stabalizing factor. Setting mu=0 implies no regularization.
  >*/


