/* This file is automatically generated. DO NOT EDIT! */

#ifndef _myradon2_h
#define _myradon2_h


void myradon2_init(int np_, int nx_, float dp_, float *p_, float *xx_);
/*< initialization >*/


void myradon2_set(float w_);
/*< set up frequency w >*/


void myradon2_lop(bool adj, bool add, int nm, int nd, sf_complex *mm, sf_complex *dd);
/*< radon linear operator >*/


void myradon2_inv(sf_complex *mm, sf_complex *adj_dd, float eps);
/*< fast Toeplitz matrix inversion for radon transform 
  mm: model to be inverted
  adj_dd: adjoint radon of data
  eps: regularization parameter
  >*/

#endif
